import AppKit
import ImageIO
import UniformTypeIdentifiers

/// Polls `NSPasteboard.general.changeCount` (there is no change notification API) and records new content.
final class ClipboardMonitor {
    private let store: ClipboardStore
    private let settings: AppSettings
    private var timer: Timer?
    private var lastChangeCount: Int

    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword", "com.typeit4me.clipping",
    ]

    init(store: ClipboardStore, settings: AppSettings) {
        self.store = store
        self.settings = settings
        lastChangeCount = NSPasteboard.general.changeCount
    }

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.4, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.tick() }
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func tick() {
        let pb = NSPasteboard.general
        let count = pb.changeCount
        guard count != lastChangeCount else { return }
        lastChangeCount = count
        guard !settings.clipboardPaused, !Paster.shared.isOwnChange(count) else { return }
        capture(from: pb)
    }

    private func capture(from pb: NSPasteboard) {
        let types = Set((pb.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.skipTypes) { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if let source, settings.ignoredBundleIDs.contains(source) { return }

        if let urls = pb.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            let paths = urls.map(\.path)
            var size = 0
            for url in urls { size += (try? url.resourceValues(forKeys: [.fileSizeKey]).fileSize) ?? 0 }
            store.add(ClipboardItem(id: UUID(), kind: .file, copiedAt: .now, filePaths: paths, byteCount: size,
                                    sourceBundleID: source, contentHash: ClipboardItem.hash(ofText: paths.joined(separator: "\n"))))
            return
        }

        if let data = pb.data(forType: .png) ?? pb.data(forType: .tiff) {
            captureImage(data, source: source)
            return
        }

        if let text = pb.string(forType: .string), !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            let kind: ClipboardItem.Kind = ClipboardItem.looksLikeLink(text) ? .link : .text
            store.add(ClipboardItem(id: UUID(), kind: kind, copiedAt: .now, text: text, byteCount: text.utf8.count,
                                    sourceBundleID: source, contentHash: ClipboardItem.hash(ofText: text)))
        }
    }

    private func captureImage(_ data: Data, source: String?) {
        let id = UUID()
        let dataStore = store.dataStore
        Task.detached(priority: .userInitiated) { [store] in
            guard let encoded = Self.encode(data) else { return }
            let imageFile = "\(id.uuidString).png"
            let previewFile = "\(id.uuidString).preview.jpg"
            do {
                try await dataStore.writeImage(encoded.png, named: imageFile)
                if let preview = encoded.preview { try await dataStore.writeImage(preview, named: previewFile) }
            } catch {
                Log.clipboard.error("image write failed: \(error.localizedDescription)")
                return
            }
            let item = ClipboardItem(id: id, kind: .image, copiedAt: .now, imageFile: imageFile,
                                     previewFile: encoded.preview == nil ? nil : previewFile,
                                     pixelWidth: encoded.width, pixelHeight: encoded.height,
                                     byteCount: encoded.png.count, sourceBundleID: source,
                                     contentHash: ClipboardItem.hash(of: encoded.png))
            await MainActor.run { store.add(item) }
        }
    }

    /// Normalises any bitmap data to PNG and produces an ≤800 px JPEG preview.
    nonisolated private static func encode(_ data: Data) -> (png: Data, preview: Data?, width: Int, height: Int)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let image = CGImageSourceCreateImageAtIndex(source, 0, nil) else { return nil }
        let width = image.width, height = image.height
        guard let png = encode(image, as: .png, quality: nil) else { return nil }
        var preview: Data?
        if max(width, height) > 800 {
            let options: [CFString: Any] = [kCGImageSourceCreateThumbnailFromImageAlways: true,
                                            kCGImageSourceThumbnailMaxPixelSize: 800,
                                            kCGImageSourceCreateThumbnailWithTransform: true]
            if let thumb = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) {
                preview = encode(thumb, as: .jpeg, quality: 0.82)
            }
        }
        return (png, preview, width, height)
    }

    nonisolated private static func encode(_ image: CGImage, as type: UTType, quality: Double?) -> Data? {
        let out = NSMutableData()
        guard let dest = CGImageDestinationCreateWithData(out, type.identifier as CFString, 1, nil) else { return nil }
        var props: [CFString: Any] = [:]
        if let quality { props[kCGImageDestinationLossyCompressionQuality] = quality }
        CGImageDestinationAddImage(dest, image, props as CFDictionary)
        guard CGImageDestinationFinalize(dest) else { return nil }
        return out as Data
    }
}
